name: '이슈 생성'
description: '깃허브 이슈를 생성하고 지라와 연동합니다'
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: key
    attributes:
      label: '🎟️ Ticket Number'
      description: '연동할 Ticket Number를 입력해주세요'
      placeholder: 'FCC-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '😸 Branch'
      description: 'Convention/name/title 양식으로 브랜치명을 작성해주세요'
      placeholder: 'Feat/dodo/home'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        |convention|purpose|
        |:---|:---|
        |Feat|새로운 기능 구현|
        |Fix|버그 수정|
        |Refactor|리팩토링|
        |Hotfix|긴급 업데이트|

  - type: input
    id: description
    attributes:
      label: '🎨 Description'
      description: '이슈에 대해 간략히 설명해주세요'
      placeholder: '어떤 기능을 구현하시나요?'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '🌽 Tasks'
      description: '이슈 구현에 필요한 하위 작업들을 남겨주세요'
      value: |
        - 
    validations:
      required: false
