name: '이슈 생성'
description: '깃허브 이슈와 지라 작업을 생성합니다'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ Ticket Number'
      description: '연동할 Ticket Number를 입력해주세요'
      placeholder: 'FCC-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '😸 Branch'
      description: 'name/label/title 양식으로 브랜치명을 작성해주세요 \n 예) dodo/feature/home'
    validations:
      required: true
      
  - type: input
    id: description
    attributes:
      label: '🎨 Description'
      description: '이슈에 대해 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '🌽 Tasks'
      description: '이슈 구현에 필요한 하위 작업들을 남겨주세요'
      value: |
        - 이곳에 지라 테스트 링크를 입력해주세요
    validations:
      required: false
