name: Create Branch and Connect Jira
on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Template Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: template-issue-parser
        with:
          template-path: '.github/ISSUE_TEMPLATE/issue-form.yml'
          
      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: '.github/ISSUE_TEMPLATE/issue-form.yml'

      - name: Debug All Outputs
        run: |
          echo "=== Template Parser Outputs ==="
          echo '${{ toJSON(steps.template-issue-parser.outputs) }}'
          echo "=== Issue Parser Outputs ==="
          echo '${{ toJSON(steps.issue-parser.outputs) }}'
          echo "=== Individual Values ==="
          echo 'Key: ${{ steps.issue-parser.outputs.issueparser_key }}'
          echo 'Branch: ${{ steps.issue-parser.outputs.issueparser_branch }}'

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.issue-parser.outputs.issueparser_key }}"
          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser_branch }}"
          
          # 빈 값 체크 및 기본값 설정
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Warning: ISSUE_NUMBER is empty, using fallback"
            ISSUE_NUMBER="issue-${{ github.event.issue.number }}"
          fi
          
          if [ -z "$ISSUE_TITLE" ]; then
            echo "Warning: ISSUE_TITLE is empty, using fallback"
            ISSUE_TITLE="feature"
          fi
          
          BRANCH_NAME="${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
          echo "Creating branch: $BRANCH_NAME"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"
