name: Create Branch and Connect Jira
on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: '.github/ISSUE_TEMPLATE/issue-form.yml'

      - name: Log Issue Parser
        run: |
          echo 'Key: ${{ steps.issue-parser.outputs.issueparser_key }}'
          echo 'Branch: ${{ steps.issue-parser.outputs.issueparser_branch }}'
          echo 'Parsed JSON: ${{ steps.issue-parser.outputs.jsonString }}'

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.issue-parser.outputs.issueparser_key }}"
          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser_branch }}"
          BRANCH_NAME="${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"
